### ISSUE TITLE
New CI3.0 doc

### ISSUE THREAD

**Issue by at15** [dyweb/guide#2]
there is already a newer version for CI3.0's doc. It's prettier.... http://www.codeigniter.com/user_guide/

But we are using a dev version ... we may have some difference.

**Comment by arrowrowe** [comment]
Got.

**Comment by at15** [comment]
@arrowrowe it's been a long time

**Comment by arrowrowe** [comment]
.........Yes...

**Comment by at15** [comment]
:+1:

**Comment by at15** [comment]
时间过的好快啊，咩毛都已经收了3次了 .w.
